package flow

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/charmbracelet/huh/spinner"

	"github.com/magma-Devs/smart-router/tools/wizard/internal/health"
	"github.com/magma-Devs/smart-router/tools/wizard/internal/laststate"
	"github.com/magma-Devs/smart-router/tools/wizard/internal/ui"
)

// ComposeFiles returns the docker compose -f args for the chosen overlay combo.
// Dashboard uses its own self-contained file (it `include`s the base); cache
// layers on top. A generated per-config port override (publishing exactly the
// listener ports the wizard assigned) is layered last so it wins.
func (s *State) composeFiles() []string {
	var f []string
	if s.Dashboard {
		f = []string{"-f", "docker/docker-compose.dashboard.yml"}
		if s.Cache {
			f = append(f, "-f", "docker/docker-compose.cache.yml")
		}
	} else {
		f = []string{"-f", "docker/docker-compose.yml"}
		if s.Cache {
			f = append(f, "-f", "docker/docker-compose.cache.yml")
		}
	}
	if ov := s.overrideRel(); ov != "" {
		f = append(f, "-f", ov)
	}
	return f
}

// overridePath returns the absolute path of the generated port-override file
// (beside the rendered config); "" until a config has been saved.
func (s *State) overridePath() string {
	if s.RenderedPath == "" {
		return ""
	}
	return strings.TrimSuffix(s.RenderedPath, ".yml") + ".compose.override.yml"
}

// overrideRel returns the override path repo-relative (for the -f arg).
func (s *State) overrideRel() string {
	full := s.overridePath()
	if full == "" {
		return ""
	}
	if rel, err := filepath.Rel(s.RepoRoot, full); err == nil {
		return filepath.ToSlash(rel)
	}
	return full
}

// specArg is the value passed to the router's --use-static-spec (via SR_SPEC):
// the bundled "specs/" dir when the catalog came from local, otherwise the
// lava-specs GitHub URL so chains absent from the image (e.g. LAV1) resolve.
// This mirrors syncHealthSpecs on the wizard's own health prober.
func (s *State) specArg() string {
	if s.Source == "local" || s.Source == "" {
		return "specs/"
	}
	return health.SpecsGitHubURL
}

// metricsPort extracts the numeric port from MetricsAddr (e.g. "0.0.0.0:7779"
// → "7779"); "" when metrics are disabled or unparseable.
func (s *State) metricsPort() string {
	if s.Metrics == "disabled" {
		return ""
	}
	addr := s.MetricsAddr()
	if i := strings.LastIndex(addr, ":"); i >= 0 && i+1 < len(addr) {
		return addr[i+1:]
	}
	return ""
}

// writePortOverride drops a generated compose override beside the rendered
// config that publishes EXACTLY the listener ports this config declares (plus
// the metrics port). The base compose keeps its hardcoded example ports so the
// bundled examples still run standalone; compose concatenates the two ports
// lists and de-dupes identical "host:container" entries, so the wizard's ports
// are added on top without disturbing the examples. Returns the override's
// repo-relative path ("" on failure or nothing to publish).
func (s *State) writePortOverride() string {
	full := s.overridePath()
	if full == "" || len(s.Listeners) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("# Generated by the smart-router wizard — DO NOT EDIT.\n")
	b.WriteString("# Publishes exactly the ports this config's listeners bind, so they're\n")
	b.WriteString("# reachable on the host. Layered last over the base/overlay compose files;\n")
	b.WriteString("# the base keeps its example ports (3360-3362) so the bundled examples still\n")
	b.WriteString("# run without the wizard.\n")
	b.WriteString("services:\n  router:\n    ports:\n")
	for _, l := range s.Listeners {
		fmt.Fprintf(&b, "      - \"%d:%d\" # %s %s\n", l.Port, l.Port, l.Chain.Index, l.Iface)
	}
	if mp := s.metricsPort(); mp != "" {
		fmt.Fprintf(&b, "      - \"%s:%s\" # router metrics\n", mp, mp)
	}
	if err := os.WriteFile(full, []byte(b.String()), 0o644); err != nil {
		return ""
	}
	return s.overrideRel()
}

// RunPlan holds the exact commands to show/execute.
type RunPlan struct {
	RenderStep string
	UpCommand  string
	DownCommand string
}

// Plan builds the render + up + down commands for the saved config. It first
// writes the generated port-override beside the rendered config, so the
// compose -f chain (built by composeFiles) can reference it.
func (s *State) Plan(relRendered string) RunPlan {
	s.writePortOverride() // before composeFiles, which adds -f <override>
	files := strings.Join(s.composeFiles(), " ")
	dir := relRendered[:strings.LastIndex(relRendered, "/")]
	tpl := strings.TrimSuffix(relRendered, ".yml") + ".template.yml"
	render := fmt.Sprintf("set -a; . %s/.env 2>/dev/null; envsubst < %s > %s", dir, tpl, relRendered)
	// SR_SPEC selects --use-static-spec inside the container: the bundled specs/
	// for a local catalog, the lava-specs GitHub URL for a remote one (so chains
	// not in the image still resolve). Only prefix it when it differs from the
	// compose default ("specs/"), to keep the common command short.
	specPrefix := ""
	if sa := s.specArg(); sa != "specs/" {
		specPrefix = fmt.Sprintf("SR_SPEC=%s ", sa)
	}
	up := fmt.Sprintf("%sSR_CONFIG=%s docker compose %s up --build", specPrefix, relRendered, files)
	down := fmt.Sprintf("docker compose %s down", files)
	return RunPlan{RenderStep: render, UpCommand: up, DownCommand: down}
}

// ShowPlan frames the run commands between top/bottom rules (NO left/right
// borders), so it reads as a panel but the command lines have nothing to their
// left — copy-paste grabs only the command. Commands sit flush at column 0.
func (s *State) ShowPlan(p RunPlan) {
	fmt.Println(ui.Section(7, "Run"))
	printRunPanel(p.RenderStep, p.UpCommand, p.DownCommand, s.writeRunScript(p), s.Dashboard)
}

// PrintLastRun reprints a previously-generated run plan (loaded from the global
// last-run store) so `wizard --last` shows the exact panel the wizard ended on,
// without re-walking the flow. The header notes when it was generated and which
// config it targets, since the user is seeing it out of context.
func PrintLastRun(rec laststate.Record) {
	fmt.Println(ui.Section(7, "Run · last generated"))
	if rec.GeneratedAt != "" || rec.ConfigPath != "" {
		fmt.Println()
		if rec.GeneratedAt != "" {
			fmt.Println("  " + ui.Hint.Render("generated ") + ui.Subtle.Render(rec.GeneratedAt))
		}
		if rec.ConfigPath != "" {
			fmt.Println("  " + ui.Hint.Render("config    ") + ui.Subtle.Render(rec.ConfigPath))
		}
	}
	printRunPanel(rec.RenderStep, rec.UpCommand, rec.DownCommand, rec.ScriptPath, rec.Dashboard)
}

// printRunPanel renders the shared run-command panel. scriptRel is the repo-
// relative run.sh path (empty to omit the "…or just run the script" block).
func printRunPanel(renderStep, upCommand, downCommand, scriptRel string, dashboard bool) {
	const w = 88
	fmt.Println()
	fmt.Println(ui.RuleTop("run command", w))
	fmt.Println()
	fmt.Println(ui.Comment.Render("# 1 · render secrets into the config the router reads:"))
	fmt.Println(renderStep)
	fmt.Println()
	fmt.Println(ui.Comment.Render("# 2 · bring the stack up:"))
	fmt.Println(ui.Accent.Render(upCommand))
	if scriptRel != "" {
		fmt.Println()
		fmt.Println(ui.Comment.Render("# …or just run the generated script:"))
		fmt.Println(ui.Accent.Render("bash " + scriptRel))
	}
	fmt.Println()
	fmt.Println(ui.Comment.Render("# teardown when you're done:"))
	fmt.Println(ui.Subtle.Render(downCommand))
	if dashboard {
		fmt.Println()
		fmt.Println(ui.Comment.Render("# dashboard (once it's up):"))
		fmt.Println(ui.Accent.Render("http://localhost:3000"))
		fmt.Println(ui.Hint.Render("login:  ") + ui.OK.Render("admin") + ui.Hint.Render(" / ") + ui.OK.Render("password"))
	}
	fmt.Println()
	fmt.Println(ui.RuleBottom(w))
}

// writeRunScript drops a run.sh beside the config (render + up in one file) and
// returns its repo-relative path, so the user can copy a single short command.
func (s *State) writeRunScript(p RunPlan) string {
	if s.RenderedPath == "" {
		return ""
	}
	dir := filepath.Dir(s.RenderedPath)
	script := filepath.Join(dir, "run.sh")
	content := "#!/usr/bin/env bash\n# Generated by the smart-router wizard.\nset -e\ncd \"$(dirname \"$0\")/" +
		relToDir(s.RepoRoot, dir) + "\"\n" + p.RenderStep + "\n" + p.UpCommand + "\n"
	if err := os.WriteFile(script, []byte(content), 0o755); err != nil {
		return ""
	}
	if rel, err := filepath.Rel(s.RepoRoot, script); err == nil {
		return filepath.ToSlash(rel)
	}
	return script
}

// LastRunRecord builds the persistable snapshot of this run plan for `--last`.
// It captures the same script path ShowPlan would surface (writing run.sh as a
// side effect, idempotently). GeneratedAt is left empty: the flow can't read the
// clock, so main stamps it before calling laststate.Save.
func (s *State) LastRunRecord(p RunPlan) laststate.Record {
	configPath := ""
	if s.RenderedPath != "" {
		if rel, err := filepath.Rel(s.RepoRoot, s.RenderedPath); err == nil {
			configPath = filepath.ToSlash(rel)
		} else {
			configPath = s.RenderedPath
		}
	}
	return laststate.Record{
		RepoRoot:    s.RepoRoot,
		ConfigPath:  configPath,
		RenderStep:  p.RenderStep,
		UpCommand:   p.UpCommand,
		DownCommand: p.DownCommand,
		ScriptPath:  s.writeRunScript(p),
		Dashboard:   s.Dashboard,
	}
}

// relToDir returns the path from dir back to repoRoot (so the script can cd to
// the repo root, where the docker compose files live).
func relToDir(repoRoot, dir string) string {
	rel, err := filepath.Rel(dir, repoRoot)
	if err != nil {
		return "."
	}
	return rel
}

// Up runs the render step then `docker compose up --build -d` from repoRoot.
func (s *State) Up(p RunPlan) error {
	render := exec.Command("bash", "-c", p.RenderStep)
	render.Dir = s.RepoRoot
	if out, err := render.CombinedOutput(); err != nil {
		return fmt.Errorf("render: %v: %s", err, out)
	}
	// up -d (detached) so we can smoke-test
	up := strings.Replace(p.UpCommand, "up --build", "up --build -d", 1)
	cmd := exec.Command("bash", "-c", up)
	cmd.Dir = s.RepoRoot
	cmd.Stdout, cmd.Stderr = os.Stdout, os.Stderr
	return cmd.Run()
}

// Smoke probes each running listener via health and reports a roll-up.
func (s *State) Smoke() {
	fmt.Println(ui.Section(8, "Smoke test"))
	if s.Prober == nil {
		fmt.Println("  " + ui.Wn.Render("! no health binary — skipping smoke"))
		return
	}
	_ = spinner.New().Title("  waiting for listeners…").
		Action(func() { time.Sleep(5 * time.Second) }).Run()

	ok := 0
	for _, l := range s.Listeners {
		url := fmt.Sprintf("http://localhost:%d", l.Port)
		env, _ := s.Prober.ProbeInline(url, l.Chain.Index, l.Iface)
		live, detail := env.Live()
		if live {
			fmt.Printf("  %s%s/%s @ :%d — %s\n", ui.Mark(), l.Chain.Index, l.Iface, l.Port, detail)
			ok++
		} else {
			fmt.Printf("  %s %s/%s @ :%d — %s\n", ui.Wn.Render("!"), l.Chain.Index, l.Iface, l.Port, detail)
		}
	}
	if ok == len(s.Listeners) {
		fmt.Println("  " + ui.OK.Render(fmt.Sprintf("%s all %d listeners answered — config runs.", ui.Check, ok)))
	} else {
		fmt.Printf("  %s\n", ui.Wn.Render(fmt.Sprintf("%d/%d answered — check 'docker compose logs router'.", ok, len(s.Listeners))))
	}
}
