//go:build testing

// This file is only compiled when the `testing` build tag is set
// (e.g. `go build -tags enterprise,testing`). Production binaries built
// without this tag do not contain key_test and therefore cannot verify
// licenses signed by the corresponding test private key. The test private
// key lives only in the internal repo's GitHub Actions secret
// LICENSE_TEST_PRIVATE_KEY and is never present in the public repo.

package licensing

import "crypto/ed25519"

func init() {
	// key_test — generated by smart-router-enterprise-internal/cmd/keygen.
	PublicKeys["key_test"] = ed25519.PublicKey{
		0x94, 0x78, 0x48, 0x85, 0x43, 0x80, 0x97, 0xa8,
		0x43, 0x0d, 0x0c, 0x7b, 0xdf, 0xbd, 0x2f, 0xbd,
		0x84, 0xd0, 0x94, 0x0b, 0x75, 0x04, 0x13, 0xa7,
		0x54, 0x5d, 0x9b, 0x19, 0xa8, 0x15, 0x13, 0x09,
	}
}
