package patchcover

import (
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

// sumSource is pkg/a.go. sumProfile holds its blocks as `go test -cover`
// (Go 1.26) records them when a test calls Sum(1, 2) and Pick(1);
// TestMeasureAgainstRealProfile checks that against the go tool.
const sumSource = `package pkg

func Sum(a, b int) int {
	if a < 0 {
		return 0
	}
	/* a block comment
	   that spans lines */
	c := a + b
	return c
}

func Never() int { x := 1; return x }

func Pick(n int) string {
	switch n {
	case 1:
		return "one"
	default:
		return "many"
	}
}
`

const sumProfile = "mode: set\n" +
	mod + "/pkg/a.go:3.24,4.11 1 1\n" + // Sum up to the if's brace
	mod + "/pkg/a.go:4.11,6.3 1 0\n" + // the if body
	mod + "/pkg/a.go:9.2,10.10 2 1\n" + // after the if
	mod + "/pkg/a.go:13.18,13.38 2 0\n" + // Never
	mod + "/pkg/a.go:15.25,16.11 1 1\n" + // Pick up to the switch's brace
	mod + "/pkg/a.go:17.9,18.15 1 1\n" + // case 1
	mod + "/pkg/a.go:19.10,20.16 1 0\n" // default

// repo lays out a two-module repository: the root module and tools/w.
func repo(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	write(t, root, "go.mod", "module "+mod+"\n\ngo 1.26\n")
	write(t, root, "tools/w/go.mod", "module "+mod+"/tools/w\n")
	write(t, root, "pkg/a.go", sumSource)
	return root
}

func added(numbers ...int) *FileDiff {
	fd := &FileDiff{}
	for _, n := range numbers {
		fd.Added = append(fd.Added, AddedLine{Number: n, Text: "x"})
	}
	return fd
}

func TestMeasureStatements(t *testing.T) {
	root := repo(t)
	cov := coverage(t, sumProfile, mod, ".")
	// Every line of every function changed, the block comment included.
	diff := map[string]*FileDiff{"pkg/a.go": added(4, 5, 6, 7, 8, 9, 10, 13, 16, 17, 18, 19, 20, 21)}

	res, err := Measure(diff, cov, root, []string{"."})
	if err != nil {
		t.Fatal(err)
	}
	// 11 statements: the if (ran), its return (not), the two lines after it
	// (ran), Never's two (not), the switch, case 1 and its return (ran), the
	// default and its return (not). The block comment holds none, so it
	// cannot dilute the result, and Never's line counts two misses.
	want := []FileResult{{Path: "pkg/a.go", Coverable: 11, Covered: 6, Uncovered: []Range{{5, 5}, {13, 13}, {19, 20}}}}
	if !reflect.DeepEqual(res.Files, want) {
		t.Fatalf("Files:\n got %+v\nwant %+v", res.Files, want)
	}
	if res.Coverable != 11 || res.Covered != 6 {
		t.Fatalf("totals: %d of %d", res.Covered, res.Coverable)
	}

	// A change to the if's condition counts the if, not the statements of its body.
	res, err = Measure(map[string]*FileDiff{"pkg/a.go": added(4)}, cov, root, []string{"."})
	if err != nil || res.Coverable != 1 || res.Covered != 1 {
		t.Fatalf("header-only change: %+v, %v", res, err)
	}
}

func TestMeasureSkipsAndBuildTags(t *testing.T) {
	root := repo(t)
	gen := "// Code generated by mockgen. DO NOT EDIT.\n\npackage pkg\n\nfunc G() int { return 1 }\n"
	write(t, root, "pkg/gen_mock.go", gen)
	write(t, root, "pkg/old_gen.go", gen)
	write(t, root, "pkg/fake_gen.go", gen)
	write(t, root, "pkg/new_mock.go", gen)
	write(t, root, "pkg/new_fake.go", gen)
	write(t, root, "pkg/ipc_windows.go", "package pkg\n\nfunc W() int { return 1 }\n")
	write(t, root, "pkg/tagged.go", "//go:build windows || darwin\n\npackage pkg\n\nfunc T() int { return 1 }\n")
	write(t, root, "pkg/netgo.go", "//go:build netgo\n\npackage pkg\n\nfunc N() int { return 1 }\n")
	write(t, root, "pkg/types.go", "package pkg\n\ntype T struct{ X int }\n")
	cov := coverage(t, sumProfile, mod, ".")

	marker := AddedLine{Number: 1, Text: "// Code generated by mockgen. DO NOT EDIT."}
	diff := map[string]*FileDiff{
		"pkg/a.go":           added(5),
		"pkg/a_test.go":      added(1),
		"pkg/testdata/x.go":  added(1),
		"pkg/_skip/x.go":     added(1),
		"pkg/old_gen.go":     added(5),                                             // regenerated: the marker was there before
		"pkg/fake_gen.go":    {Added: []AddedLine{marker, {Number: 5, Text: "x"}}}, // the change typed the marker itself
		"pkg/new_mock.go":    {New: true, Added: []AddedLine{marker, {Number: 5}}}, // a new file under a generator's name
		"pkg/new_fake.go":    {New: true, Added: []AddedLine{marker, {Number: 5}}}, // a new file whose name no generator writes
		"pkg/ipc_windows.go": added(3),                                             // built only on windows
		"pkg/tagged.go":      added(5),                                             // built only on windows and darwin
		"pkg/netgo.go":       added(5),                                             // built by the release, never by the tests
		"pkg/types.go":       added(3),                                             // no statement at all
		"README.md":          added(1),
	}
	res, err := Measure(diff, cov, root, []string{".", "tools/w"})
	if err != nil {
		t.Fatal(err)
	}
	if want := []string{"pkg/_skip/x.go", "pkg/a_test.go", "pkg/new_mock.go", "pkg/old_gen.go", "pkg/testdata/x.go"}; !reflect.DeepEqual(res.Skipped, want) {
		t.Errorf("Skipped = %v, want %v", res.Skipped, want)
	}
	if want := []string{"pkg/ipc_windows.go", "pkg/tagged.go"}; !reflect.DeepEqual(res.NoStatements, want) {
		t.Errorf("NoStatements = %v, want %v", res.NoStatements, want)
	}
	var measured []string
	for _, f := range res.Files {
		measured = append(measured, f.Path)
		if f.Path != "pkg/a.go" && (f.Coverable != 1 || f.Covered != 0) {
			t.Errorf("%s: %d of %d, want 0 of 1", f.Path, f.Covered, f.Coverable)
		}
	}
	if want := []string{"pkg/a.go", "pkg/fake_gen.go", "pkg/netgo.go", "pkg/new_fake.go"}; !reflect.DeepEqual(measured, want) {
		t.Errorf("measured %v, want %v", measured, want)
	}
}

func TestMeasureErrors(t *testing.T) {
	root := repo(t)
	cov := coverage(t, sumProfile, mod, ".")
	for name, tc := range map[string]struct {
		file, content, want string
		modules             []string
	}{
		"module without a profile": {"tools/w/x.go", "package w\n\nfunc F() int { return 1 }\n", "no coverage profile", []string{"."}},
		"unparsable file":          {"pkg/bad.go", "package pkg\n\nfunc (\n", "expected", []string{"."}},
		"missing file":             {"pkg/gone.go", "", "no such file", []string{"."}},
	} {
		if tc.content != "" {
			write(t, root, tc.file, tc.content)
		}
		_, err := Measure(map[string]*FileDiff{tc.file: added(3)}, cov, root, tc.modules)
		if err == nil || !strings.Contains(err.Error(), tc.want) {
			t.Errorf("%s: err = %v, want it to mention %q", name, err, tc.want)
		}
	}

	bare := t.TempDir()
	write(t, bare, "x.go", "package x\n")
	if _, err := Measure(map[string]*FileDiff{"x.go": added(1)}, NewCoverage(), bare, []string{"."}); err == nil {
		t.Error("a Go file outside any module must fail the run")
	}
}

func TestPassAndPercent(t *testing.T) {
	for _, tc := range []struct {
		covered, coverable, min int
		pass                    bool
		percent                 float64
	}{
		{0, 0, 80, true, 100},
		{4, 5, 80, true, 80},
		{3, 4, 80, false, 75},
		{0, 3, 0, true, 0},
		{2, 3, 100, false, 200.0 / 3},
	} {
		r := Result{Covered: tc.covered, Coverable: tc.coverable}
		if r.Pass(tc.min) != tc.pass || r.Percent() != tc.percent {
			t.Errorf("%d of %d at %d%%: got pass=%v percent=%v", tc.covered, tc.coverable, tc.min, r.Pass(tc.min), r.Percent())
		}
	}
}

func TestOutsidePackages(t *testing.T) {
	for file, want := range map[string]bool{
		"a.go":               false,
		"pkg/a.go":           false,
		"pkg/testdata/a.go":  true,
		"testdata/a.go":      true,
		".github/x/a.go":     true,
		"pkg/_vendor/a.go":   true,
		"pkg/data_test/a.go": false,
	} {
		if got := outsidePackages(file); got != want {
			t.Errorf("outsidePackages(%q) = %v, want %v", file, got, want)
		}
	}
}

func TestGeneratorName(t *testing.T) {
	for file, want := range map[string]bool{
		"x/service.pb.go":     true,
		"x/service.pb.gw.go":  true,
		"x/chainlib_mock.go":  true,
		"x/mock_websocket.go": true,
		"x/kind_string.go":    true,
		"x/zz_generated.go":   true,
		"x/handler.go":        false,
		"x/mocking.go":        false,
	} {
		if got := generatorName(file); got != want {
			t.Errorf("generatorName(%q) = %v, want %v", file, got, want)
		}
	}
}

// loopsSource holds every other kind of statement: loops, a type switch, a
// select, a function literal and a label. realCoverage runs it with
// Loops([]int{1}, make(chan int), 1), so the string case, the receive case
// and the literal's body never run.
const loopsSource = `package pkg

func Loops(xs []int, ch chan int, v any) int {
	total := 0
	for i := 0; i < len(xs); i++ {
		total += xs[i]
	}
	for _, x := range xs {
		total -= x
	}
	switch v.(type) {
	case int:
		total++
	case string:
		total--
	}
	select {
	case n := <-ch:
		total += n
	default:
		total *= 2
	}
	run := func() { total = 0 }
	_ = run
outer:
	for {
		break outer
	}
	return total
}
`

// realCoverage runs the go tool on the repository and returns the profile it
// writes. Measure is checked against it, so a change in how cover lays out its
// blocks shows up here rather than as a wrong verdict on a pull request.
func realCoverage(t *testing.T, root string) *Coverage {
	t.Helper()
	goTool, err := exec.LookPath("go")
	if err != nil {
		t.Skip("the go tool is not on PATH")
	}
	write(t, root, "pkg/a_test.go", "package pkg\n\nimport \"testing\"\n\nfunc TestAll(t *testing.T) {\n\tSum(1, 2)\n\tPick(1)\n\tLoops([]int{1}, make(chan int), 1)\n}\n")
	write(t, root, "pkg/loops.go", loopsSource)
	profile := filepath.Join(t.TempDir(), "cover.out")
	cmd := exec.Command(goTool, "test", "./...", "-count=1", "-covermode=set", "-coverpkg=./...", "-coverprofile="+profile)
	cmd.Dir = root
	cmd.Env = append(os.Environ(), "GOWORK=off")
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("go test: %v\n%s", err, out)
	}
	f, err := os.Open(profile)
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()
	cov := NewCoverage()
	if err := cov.AddProfile(f, mod, "."); err != nil {
		t.Fatal(err)
	}
	return cov
}

func TestMeasureAgainstRealProfile(t *testing.T) {
	root := repo(t)
	cov := realCoverage(t, root)
	every := func(from, to int) *FileDiff {
		fd := &FileDiff{}
		for n := from; n <= to; n++ {
			fd.Added = append(fd.Added, AddedLine{Number: n, Text: "x"})
		}
		return fd
	}
	res, err := Measure(map[string]*FileDiff{"pkg/a.go": every(4, 21), "pkg/loops.go": every(4, 30)}, cov, root, []string{"."})
	if err != nil {
		t.Fatal(err)
	}
	want := []FileResult{
		{Path: "pkg/a.go", Coverable: 11, Covered: 6, Uncovered: []Range{{5, 5}, {13, 13}, {19, 20}}},
		// 21 statements: a for header is one statement, its init and post are
		// part of it; the receive of a select case is part of the case; the
		// label is not one; line 23 holds two, the literal's body never ran.
		{Path: "pkg/loops.go", Coverable: 21, Covered: 16, Uncovered: []Range{{14, 15}, {18, 19}, {23, 23}}},
	}
	if !reflect.DeepEqual(res.Files, want) {
		t.Fatalf("against a real profile:\n got %+v\nwant %+v", res.Files, want)
	}
}
