// Package emit renders the smart-router YAML config from the wizard's collected
// state, plus the secret scaffold (.env + ${VAR} template + render).
//
// Mirrors scripts/wizard/lib/emit.sh. Schema (per protocol/common/endpoints.go):
//   metrics-listen-address, cache-be?, endpoints[], direct-rpc[], backup-direct-rpc[]
// Each provider: name/chain-id/api-interface/node-urls[{url, addons?, auth-config?}].
// The router reads YAML literally (no ${ENV} expansion), so auth uses ${VAR}
// placeholders rendered from a .env via Render (an envsubst equivalent).
package emit

import (
	"fmt"
	"os"
	"regexp"
	"slices"
	"sort"
	"strings"
)

// Auth describes an endpoint credential.
type Auth struct {
	Var   string // env var name, e.g. RPC_KEY_ETH1
	Kind  string // "header:<Name>" or "query:<param>"
	Value string // the secret value the user entered (seeds .env; never in YAML)
}

// Upstream is one provider entry under direct-rpc / backup-direct-rpc.
type Upstream struct {
	Name    string
	ChainID string
	Iface   string
	URLs    []string // http first, then optional ws
	Addons  []string
	Auth    *Auth
}

// Listener is one endpoints[] row.
type Listener struct {
	ChainID string
	Iface   string
	Port    int
}

// Config is the full wizard state to render.
type Config struct {
	Metrics   string // "0.0.0.0:7779" or "disabled"
	Cache     bool
	Listeners []Listener
	Primary   []Upstream
	Backup    []Upstream
}

// EnvVars returns the unique set of auth var names across all upstreams.
func (c *Config) EnvVars() []string {
	set := map[string]bool{}
	for _, u := range append(append([]Upstream{}, c.Primary...), c.Backup...) {
		if u.Auth != nil && u.Auth.Var != "" {
			set[u.Auth.Var] = true
		}
	}
	out := make([]string, 0, len(set))
	for k := range set {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// YAML renders the template form (${VAR} intact).
func (c *Config) YAML() string {
	var b strings.Builder
	b.WriteString("# Smart Router config — generated by tools/wizard.\n")
	b.WriteString("# Edit the *.template.yml and re-render; do not hand-edit the rendered *.yml.\n#\n")
	b.WriteString("# Render: set -a; . ./.env; envsubst < <name>.template.yml > <name>.yml\n")
	b.WriteString("# TODO(cross-validation): add a 'cross-validation:' block to enable read\n")
	b.WriteString("#   fan-out verification (see protocol/.../cross_validation_policy.go).\n\n")

	if c.Metrics == "disabled" {
		b.WriteString("metrics-listen-address: \"disabled\"\n")
	} else {
		m := c.Metrics
		if m == "" {
			m = "0.0.0.0:7779"
		}
		fmt.Fprintf(&b, "metrics-listen-address: %q\n", m)
	}
	if c.Cache {
		b.WriteString("cache-be: \"cache:20100\"\n")
	}
	b.WriteString("\nendpoints:\n")
	for _, l := range c.Listeners {
		fmt.Fprintf(&b, "  - listen-address: \"0.0.0.0:%d\"\n", l.Port)
		fmt.Fprintf(&b, "    chain-id: %q\n", l.ChainID)
		fmt.Fprintf(&b, "    api-interface: %q\n", l.Iface)
		fmt.Fprintf(&b, "    network-address: \"0.0.0.0:%d\"\n", l.Port)
	}
	b.WriteString("\n")
	writeRPCBlock(&b, "direct-rpc", c.Primary)
	if len(c.Backup) > 0 {
		b.WriteString("\n")
		writeRPCBlock(&b, "backup-direct-rpc", c.Backup)
	}
	return b.String()
}

// writeRPCBlock renders one direct-rpc / backup-direct-rpc block. Each upstream is
// ONE provider whose node-urls are: the base http url (URLs[0]), then any ws urls,
// then one addon-tagged node-url per capability — all sharing the same provider.
//
// This single-provider / multi-node-url layout is load-bearing; it's the only shape
// that boots clean on the real router for the capabilities the wizard emits. The
// reasoning, verified live against lava.build:
//
//   - The chain router is built PER PROVIDER (chain_router.go:240) and requires the
//     base "||" collection plus, for a subscription-tagged spec (EVM jsonrpc declares
//     eth_subscribe), a "|websocket|" collection. Both the base http url and the ws
//     url live in this one provider, so both collections are satisfied here.
//
//   - An "extension" (archive is the only one across Lava specs) is only routable
//     when the base collection coexists in the SAME provider's router: archive's
//     required set always includes the base "||" it extends. A separate archive-only
//     provider therefore fails "not all requirements supported in chainRouter" in
//     BOTH `health` and a real boot. Putting the archive node-url on the base
//     provider gives it that base collection. (For non-subscription interfaces —
//     rest/grpc — this is the shape that boots; archive verifies cleanly.)
//
//   - Add_ons (debug/trace/bundler/…) are admitted straight from the node-url
//     declaration and verify fine as extra node-urls on the base provider.
//
// Note on EVM-jsonrpc + archive specifically: the router widens an archive
// verification to "archive,websocket" on a subscription-tagged spec
// (getExtensionsForVerification, chain_fetcher.go:274), which no single public
// gateway serves over one connection — so archive is unservable for EVM-jsonrpc via
// a public gateway in ANY layout. The wizard never emits it there: probeOneAddon
// (flow/endpoints.go) gates every addon on a live `health` verification, and that
// widening makes the archive probe fail for EVM-jsonrpc. The public gateways are
// themselves archive nodes, so archive-depth reads still resolve through the base
// url. This emitter just lays out whatever the probe confirmed; it doesn't decide
// which capabilities are supported.
func writeRPCBlock(b *strings.Builder, key string, ups []Upstream) {
	fmt.Fprintf(b, "%s:\n", key)
	for _, u := range ups {
		if len(u.URLs) == 0 {
			continue
		}
		writeProvider(b, u.Name, u)
	}
}

// subscriptionIface reports whether an api-interface's spec carries subscriptions
// (eth_subscribe for jsonrpc, /websocket for tendermintrpc). On such a spec the
// router ws-widens an archive verification — see archiveNeedsSkipPruning.
func subscriptionIface(iface string) bool {
	return iface == "jsonrpc" || iface == "tendermintrpc"
}

// archiveNeedsSkipPruning reports whether this upstream's archive node-url must
// carry `skip-verifications: ["pruning"]` to boot.
//
// On a subscription-tagged spec the router widens the archive extension's startup
// verification (named "pruning" in the specs) to {archive,websocket}
// (getExtensionsForVerification, chain_fetcher.go:283). When the upstream ALSO
// declares a ws url, that widened verification is exercised and no single public
// gateway serves the {archive,websocket} combination over one connection, so the
// provider is excluded ("no chain proxy supporting requested extensions") and the
// endpoint can't be served. Skipping just the `pruning` verification on the
// archive node-url removes exactly that widened probe; the base + ws node-urls keep
// all their verifications, and archive-depth state reads still route via the base
// url. (Live-proven: ETH1 jsonrpc base+ws+archive boots clean with this and nothing
// else — no --skip-websocket-verification flag needed.)
//
// Without a ws url there's nothing to widen the archive verification against, so the
// skip isn't needed (and isn't emitted) — archive verifies cleanly on its own.
func archiveNeedsSkipPruning(u Upstream) bool {
	if !subscriptionIface(u.Iface) || len(u.URLs) < 2 {
		return false
	}
	return slices.Contains(u.Addons, "archive")
}

// writeProvider emits a single provider entry: the upstream's base http url
// (URLs[0]) with auth attached, then any further urls (ws), then one addon-tagged
// node-url per capability in u.Addons. Every capability shares this one provider so
// each addon/extension router resolves against the base collection alongside it.
func writeProvider(b *strings.Builder, name string, u Upstream) {
	fmt.Fprintf(b, "  - name: %q\n", name)
	fmt.Fprintf(b, "    chain-id: %q\n", u.ChainID)
	fmt.Fprintf(b, "    api-interface: %q\n", u.Iface)
	b.WriteString("    node-urls:\n")
	for i, url := range u.URLs {
		fmt.Fprintf(b, "      - url: %q\n", url)
		// Auth attaches to the base (first) url only.
		if i == 0 && u.Auth != nil && u.Auth.Var != "" {
			writeAuth(b, u.Auth)
		}
	}
	// One addon-tagged node-url per capability, reusing the base http url (URLs[0]).
	skipPruning := archiveNeedsSkipPruning(u)
	for _, a := range u.Addons {
		fmt.Fprintf(b, "      - url: %q\n", u.URLs[0])
		fmt.Fprintf(b, "        addons: [%s]\n", quoteList([]string{a}))
		// archive + ws on a subscription spec: skip the ws-widened `pruning`
		// verification so the provider isn't excluded at startup (see
		// archiveNeedsSkipPruning). Scoped to the archive node-url only.
		if a == "archive" && skipPruning {
			fmt.Fprintf(b, "        skip-verifications: [%s]\n", quoteList([]string{"pruning"}))
		}
	}
}

// quoteList renders a YAML flow sequence of quoted strings: `"a", "b"`.
func quoteList(items []string) string {
	quoted := make([]string, len(items))
	for i, it := range items {
		quoted[i] = fmt.Sprintf("%q", it)
	}
	return strings.Join(quoted, ", ")
}

func writeAuth(b *strings.Builder, a *Auth) {
	b.WriteString("        auth-config:\n")
	switch {
	case strings.HasPrefix(a.Kind, "header:"):
		name := strings.TrimPrefix(a.Kind, "header:")
		b.WriteString("          auth-headers:\n")
		fmt.Fprintf(b, "            %s: \"${%s}\"\n", name, a.Var)
	case strings.HasPrefix(a.Kind, "query:"):
		param := strings.TrimPrefix(a.Kind, "query:")
		fmt.Fprintf(b, "          auth-query: \"%s=${%s}\"\n", param, a.Var)
	}
}

// EnvTemplate returns the .env scaffold: each auth var seeded with the value
// the user entered (or CHANGE_ME if they left it blank). Secrets live here, not
// in the YAML.
func (c *Config) EnvTemplate() string {
	vals := map[string]string{}
	for _, u := range append(append([]Upstream{}, c.Primary...), c.Backup...) {
		if u.Auth != nil && u.Auth.Var != "" {
			v := u.Auth.Value
			if v == "" {
				v = "CHANGE_ME"
			}
			vals[u.Auth.Var] = v
		}
	}
	var b strings.Builder
	b.WriteString("# Secrets for the generated smart-router config — gitignored, never commit.\n")
	b.WriteString("# Pre-filled from the wizard; edit if needed. Rendered into the *.yml as ${VAR}.\n")
	for _, v := range c.EnvVars() {
		fmt.Fprintf(&b, "%s=%s\n", v, vals[v])
	}
	return b.String()
}

var envRef = regexp.MustCompile(`\$\{([A-Za-z_][A-Za-z0-9_]*)\}`)

// Render expands ${VAR} in template using values from the env map (an envsubst
// equivalent). Unknown vars are left literal so Lint can flag them.
func Render(template string, env map[string]string) string {
	return envRef.ReplaceAllStringFunc(template, func(m string) string {
		name := envRef.FindStringSubmatch(m)[1]
		if v, ok := env[name]; ok {
			return v
		}
		return m
	})
}

// LoadEnv parses a KEY=VALUE .env file into a map.
func LoadEnv(path string) (map[string]string, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	out := map[string]string{}
	for _, line := range strings.Split(string(b), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if k, v, ok := strings.Cut(line, "="); ok {
			out[strings.TrimSpace(k)] = strings.TrimSpace(v)
		}
	}
	return out, nil
}

// Lint checks a rendered config for the failures that make the router boot then
// silently do nothing. Returns a slice of problems (empty == clean).
func (c *Config) Lint(rendered string) []string {
	var problems []string
	// Every listener must have a matching direct-rpc upstream.
	have := map[string]bool{}
	for _, u := range c.Primary {
		have[u.ChainID+"|"+u.Iface] = true
	}
	for _, l := range c.Listeners {
		if !have[l.ChainID+"|"+l.Iface] {
			problems = append(problems, fmt.Sprintf("listener %s/%s has no direct-rpc upstream", l.ChainID, l.Iface))
		}
	}
	if strings.Contains(rendered, "CHANGE_ME") || envRef.MatchString(rendered) {
		problems = append(problems, "unfilled secret/placeholder remains in rendered config")
	}
	return problems
}
