#!/bin/bash
# RESP cache backend integration lane (docs/RESP-CACHE.md).
#
# Runs the router against a REAL Valkey (docker) instead of the cache sidecar:
#
#   valkey (docker, 127.0.0.1:63790, volatile-lru)
#   smartrouter (:3360) --resp-cache-addresses 127.0.0.1:63790
#
# RUN_DEMO=1 additionally proves the flow end to end: relay -> populate ->
# repeat relay -> cache hit (smartrouter_cache_success_total > 0) and the
# entries visibly stored in valkey under the key prefix (valkey-cli --scan).
#
# The router and valkey are LEFT RUNNING for interactive testing; stop
# instructions are printed at the end.
__dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

LOGS_DIR=${__dir}/../../debugging/logs
mkdir -p "$LOGS_DIR"
LOGS_DIR=$(cd "$LOGS_DIR" && pwd)

PROJECT_ROOT=$(cd "${__dir}"/../.. && pwd)
CONFIG_FILE="$PROJECT_ROOT/config/smartrouter_examples/smartrouter_eth_resp_lane.yml"
VALKEY_NAME="smartrouter-resp-valkey"
VALKEY_PORT=63790
ROUTER_PORT=3360
METRICS_PORT=7779
KEY_PREFIX="sr"

command -v docker >/dev/null || { echo "ERROR: this lane needs docker (for valkey)"; exit 1; }

# Fresh start: previous instances of THIS lane only (unrelated screens are
# left alone). Quitting the screen does not reliably kill the piped router
# child, so also kill any smartrouter still holding this lane's ports.
screen -S smartrouter-resp -X quit 2>/dev/null || true
for port in $ROUTER_PORT $METRICS_PORT; do
    for pid in $(lsof -nP -iTCP:$port -sTCP:LISTEN -t 2>/dev/null); do
        if ps -p "$pid" -o comm= | grep -q smartrouter; then
            echo "[Setup] stopping previous lane router (pid $pid, port $port)"
            kill "$pid" 2>/dev/null || true
        fi
    done
done
docker rm -f "$VALKEY_NAME" >/dev/null 2>&1 || true
sleep 1

# Pre-flight: after our own cleanup the lane's ports must be free — a FOREIGN
# process here would silently absorb the health checks and demo probes.
for port in $ROUTER_PORT $METRICS_PORT $VALKEY_PORT; do
    if lsof -nP -iTCP:$port -sTCP:LISTEN >/dev/null 2>&1; then
        echo "ERROR: port $port is held by a process this lane does not own:"
        lsof -nP -iTCP:$port -sTCP:LISTEN | sed 's/^/  /'
        echo "Stop it (screen -ls may show which lane started it), then re-run."
        exit 1
    fi
done

echo "============================================"
echo "Smart Router RESP Cache Backend Lane"
echo "============================================"

echo "[Setup] installing binaries"
make -C "$PROJECT_ROOT" install

echo "[Setup] starting valkey (docker, 127.0.0.1:${VALKEY_PORT}, volatile-lru)"
docker run -d --rm --name "$VALKEY_NAME" -p 127.0.0.1:${VALKEY_PORT}:6379 \
  valkey/valkey:7.2 valkey-server --maxmemory 256mb --maxmemory-policy volatile-lru >/dev/null
for i in $(seq 1 20); do
    docker exec "$VALKEY_NAME" valkey-cli ping >/dev/null 2>&1 && break
    sleep 0.5
done
docker exec "$VALKEY_NAME" valkey-cli ping >/dev/null || { echo "ERROR: valkey did not come up"; exit 1; }
echo "  valkey: UP"

# Upstreams: overridable, public defaults.
export ETH_RPC_URL_1="${ETH_RPC_URL_1:-https://ethereum-rpc.publicnode.com}"
export ETH_RPC_URL_2="${ETH_RPC_URL_2:-https://mainnet.gateway.tenderly.co}"

cat > "$CONFIG_FILE" <<EOF
# Generated by init_smartrouter_eth_resp_cache.sh — the RESP lane config.
# The resp-cache backend is passed via --resp-cache-addresses on the command
# line to exercise the flag path; this file carries endpoints only.
endpoints:
  - listen-address: "0.0.0.0:${ROUTER_PORT}"
    chain-id: "ETH1"
    api-interface: "jsonrpc"
    network-address: "0.0.0.0:${ROUTER_PORT}"

direct-rpc:
  - name: "eth-rpc-1"
    chain-id: "ETH1"
    api-interface: "jsonrpc"
    node-urls:
      - url: "$ETH_RPC_URL_1"
        skip-verifications:
          - chain-id
          - pruning
  - name: "eth-rpc-2"
    chain-id: "ETH1"
    api-interface: "jsonrpc"
    node-urls:
      - url: "$ETH_RPC_URL_2"
        skip-verifications:
          - chain-id
          - pruning
EOF

echo "[Setup] starting smart router (:${ROUTER_PORT}) with --resp-cache-addresses 127.0.0.1:${VALKEY_PORT}"
# NOTE: the config path must be RELATIVE to the project root — the router's
# config loader resolves the argument against its search paths.
screen -d -m -S smartrouter-resp bash -c "cd $PROJECT_ROOT && source ~/.bashrc; smartrouter \
config/smartrouter_examples/smartrouter_eth_resp_lane.yml \
--log-level debug \
--resp-cache-addresses \"127.0.0.1:${VALKEY_PORT}\" \
--use-static-spec $PROJECT_ROOT/specs/ethereum.json \
--skip-websocket-verification \
--metrics-listen-address ':${METRICS_PORT}' 2>&1 | tee $LOGS_DIR/SMARTROUTER_RESP.log" && sleep 0.25

# The definitive startup marker is OUR router logging its backend selection —
# port probes alone can false-green against a foreign process.
ROUTER_OK=0
for i in $(seq 1 30); do
    if grep -q "resp-cache backend configured" "$LOGS_DIR/SMARTROUTER_RESP.log" 2>/dev/null; then
        ROUTER_OK=1
        break
    fi
    if grep -q "^Error:" "$LOGS_DIR/SMARTROUTER_RESP.log" 2>/dev/null; then
        break
    fi
    sleep 1
done
if [[ "$ROUTER_OK" != "1" ]]; then
    echo "ERROR: router did not come up with the RESP backend — last log lines:"
    tail -5 "$LOGS_DIR/SMARTROUTER_RESP.log" 2>/dev/null | sed 's/^/  /'
    exit 1
fi
echo "  router: UP with resp-cache backend (logs: $LOGS_DIR/SMARTROUTER_RESP.log)"

if [[ "$RUN_DEMO" == "1" ]]; then
    echo ""
    echo "[Demo] relay -> populate -> repeat -> RESP-backed cache hit"
    RELAY='{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}'
    relay() { curl -sf -m 10 -X POST "http://127.0.0.1:${ROUTER_PORT}" -H 'Content-Type: application/json' -d "$RELAY" >/dev/null; }
    hits() { curl -sf "http://127.0.0.1:${METRICS_PORT}/metrics" | awk '/^smartrouter_cache_success_total/ {sum += $NF} END {printf "%d", sum}'; }

    # Give endpoint verification a moment, then warm + re-request until a hit
    # lands (the populator write is asynchronous).
    sleep 5
    DEMO_OK=0
    for i in $(seq 1 20); do
        relay || true
        sleep 0.5
        relay || true
        sleep 0.5
        if [[ "$(hits)" -gt 0 ]]; then DEMO_OK=1; break; fi
    done

    STORED_KEYS=$(docker exec "$VALKEY_NAME" valkey-cli --scan --pattern "${KEY_PREFIX}:*" | head -5)
    echo ""
    if [[ "$DEMO_OK" == "1" && -n "$STORED_KEYS" ]]; then
        echo "DEMO PASS:"
        echo "  smartrouter_cache_success_total > 0 (served from the RESP backend)"
        echo "  entries in valkey under '${KEY_PREFIX}:':"
        echo "$STORED_KEYS" | sed 's/^/    /'
    else
        echo "DEMO FAIL:"
        echo "  cache hits: $(hits)   stored keys: $(docker exec "$VALKEY_NAME" valkey-cli --scan --pattern "${KEY_PREFIX}:*" | wc -l | tr -d ' ')"
        echo "  check $LOGS_DIR/SMARTROUTER_RESP.log (upstreams reachable? resp-cache configured?)"
        exit 1
    fi
fi

echo ""
echo "============================================"
echo "RESP cache lane ready"
echo "============================================"
echo "Router:   http://127.0.0.1:${ROUTER_PORT}   (metrics: :${METRICS_PORT})"
echo "Valkey:   127.0.0.1:${VALKEY_PORT}          (docker: ${VALKEY_NAME})"
echo ""
echo "Try it:"
echo "  curl -s -X POST http://127.0.0.1:${ROUTER_PORT} -H 'Content-Type: application/json' \\"
echo "    -d '{\"jsonrpc\":\"2.0\",\"method\":\"eth_blockNumber\",\"params\":[],\"id\":1}'"
echo ""
echo "Inspect the backend:"
echo "  docker exec ${VALKEY_NAME} valkey-cli --scan --pattern '${KEY_PREFIX}:*'"
echo "  curl -s http://127.0.0.1:${METRICS_PORT}/metrics | grep smartrouter_resp_cache"
echo ""
echo "To stop:"
echo "  screen -S smartrouter-resp -X quit; docker rm -f ${VALKEY_NAME}"
echo "============================================"
