#!/bin/bash
# Cross-Validation — DEFAULT LANE (PRD UC-7: no cross-validation configuration)
#
# The other lane (init_smartrouter_cv_demo.sh) shows what the feature does. This
# one shows what a deployment that never adopts it does. It boots the SAME six
# providers on the SAME simulator ports, and the config differs by exactly three
# things: no `cross-validation:` block, no `group-label:` on any provider, and
# the listen port. That is deliberate — it is what makes
#
#   diff debugging/smartrouter_cv_default.yml debugging/smartrouter_cv_demo.yml
#
# a readable answer to "what does adopting this feature actually add?" rather
# than a diff dominated by an unrelated change in fleet size.
#
# It is a separate lane rather than a flag on the other one because the thing
# under test IS the absence of configuration: a router loaded with policies can
# never demonstrate it, whatever request you send. The two lanes share their
# helpers via _cv_lane_lib.sh, so "a second script" costs a config emitter and a
# checks function, not a second copy of the ownership contract.
#
# THE SIMULATOR IS SHARED, and this lane drives the same provider ids as the demo
# lane — run them one at a time.
#
# USAGE
#   scripts/pre_setups/init_smartrouter_cv_default.sh          # bring it up + check
#   scripts/pre_setups/init_smartrouter_cv_default.sh --check  # re-run the checks
#   scripts/pre_setups/init_smartrouter_cv_default.sh --status
#   scripts/pre_setups/init_smartrouter_cv_default.sh --stop
#
# ENVIRONMENT
#   SIM_DIR         provider_simulator checkout (searched for by default)
#   ROUTER_PORT (3399)  METRICS_PORT (7793)   SKIP_CHECK=1
#
# OWNERSHIP SAFETY: same contract as the demo lane, from the same shared
# implementation — no `killall`, reclaims only a process it recorded starting or
# one whose command line names this checkout's ABSOLUTE config path, and refuses
# to run on ports it does not own.

__dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
PROJECT_ROOT=$(cd "${__dir}"/../.. && pwd)
source "$__dir"/../useful_commands.sh

LOGS_DIR="${PROJECT_ROOT}/debugging/logs"
mkdir -p "$LOGS_DIR"

ROUTER_PORT="${ROUTER_PORT:-3399}"
METRICS_PORT="${METRICS_PORT:-7793}"

source "$__dir"/_cv_lane_lib.sh

LANE="$(lane_tag)"
ROUTER_SCREEN="sr-cv-default-${LANE}"
CONFIG_REL="debugging/smartrouter_cv_default.yml"
CONFIG_FILE="${PROJECT_ROOT}/${CONFIG_REL}"
PIDFILE="${PROJECT_ROOT}/debugging/.cv-default-router.pid"
ROUTER_LOG="${LOGS_DIR}/SMARTROUTER_CV_DEFAULT.log"
SIM_LOG="${LOGS_DIR}/CV_DEFAULT_SIM.log"
SPEC_FILE="${PROJECT_ROOT}/specs/ethereum.json"

# The SAME six providers as the demo lane — see the header.
SIM_PORTS="18545 18546 18547 18560 18561 18562"
FLEET_SIZE=6
BLOCK="0x1000000"
METHOD="eth_getBalance"          # the method the OTHER lane mandates a policy on
WARM_METHOD="eth_getBlockByNumber"  # used only for readiness, so METHOD's counters stay clean

HDR=""

teardown() {
    echo "[Teardown] stopping this lane's resources (nothing else is signalled)"
    reclaim_owned "$PIDFILE" "router"
    reclaim_by_identity "$ROUTER_PORT" "$CONFIG_FILE" "router"
    screen -S "$ROUTER_SCREEN" -X quit >/dev/null 2>&1 || true
    echo "  the provider_simulator is shared infrastructure — left running"
    echo "[Teardown] done"
}

# fleet_clean : this lane's providers honest and fast, stated explicitly.
# POST /reset/all is unscoped and would wipe other harnesses' fixtures.
fleet_clean() {
    sim_scenario '{"providers":{
        "eth-sim:1":{"latency_ms":0,"responses":{}},
        "eth-sim:2":{"latency_ms":0,"responses":{}},
        "eth-sim:3":{"latency_ms":0,"responses":{}},
        "eth-sim:4":{"latency_ms":0,"responses":{}},
        "eth-sim:5":{"latency_ms":0,"responses":{}},
        "eth-sim:6":{"latency_ms":0,"responses":{}}}}'
}

emit_config() {
    cat <<EOF
# GENERATED by scripts/pre_setups/init_smartrouter_cv_default.sh — do not hand-edit.
#
# UC-7: the pre-feature shape. The fleet is identical to the demo lane's; what is
# NOT here is the point — no cross-validation: block, no group-label: on any
# provider, no thresholds. Everything below is config that existed before
# per-method policies did.
endpoints:
  - listen-address: "0.0.0.0:${ROUTER_PORT}"
    chain-id: "ETH1"
    api-interface: "jsonrpc"
    network-address: "0.0.0.0:${ROUTER_PORT}"

direct-rpc:
EOF
    local i=0 port
    for port in $SIM_PORTS; do
        i=$((i + 1))
        cat <<EOF
  - name: "sim-$i"
    chain-id: "ETH1"
    api-interface: "jsonrpc"
    node-urls:
      - url: "http://127.0.0.1:$port"
        timeout: 10s
        skip-verifications: [chain-id, pruning]
EOF
    done
}

write_config() { write_config_atomic "$CONFIG_FILE" emit_config; }

checks() {
    echo ""
    echo "============================================"
    echo "UC-7 — no cross-validation configuration"
    echo "============================================"
    fleet_clean
    local snap before after

    echo ""
    echo "[1] the startup log carries no policy layout at all"
    # A negative grep alone cannot tell "the line is absent" from "the log is
    # absent" — both exit non-zero — so anchor on a line that MUST be there first.
    if ! grep -q "RPCSmartRouter started" "$ROUTER_LOG" 2>/dev/null; then
        fail "cannot read this router's startup log ($ROUTER_LOG) — nothing was verified"
    elif grep -q "cross-validation per-method policies loaded" "$ROUTER_LOG" 2>/dev/null; then
        fail "a policy-layout line was logged — this config has no policies"
    else
        pass "the log is readable, and the policy-layout line is absent from it"
        pass "absent, not 'policies=0' — the resolver was never populated"
    fi

    echo ""
    echo "[2] '$METHOD' — the method the demo lane MANDATES — is plain here"
    snap=$(metrics_scrape)
    before=$(metric_in "$snap" cross_validation_requests_total "method=\"${METHOD}\"")
    call "$METHOD" "[\"$(addr 71)\",\"$BLOCK\"]" >/dev/null
    if cv_present; then
        fail "cross-validation happened with no policy and no caller headers"
        grep -i '^lava-cross-validation-' "$HDR" | tr -d '\r' | sed 's/^/        /'
    else
        pass "one provider, one relay — nothing changed for existing callers"
    fi
    snap=$(metrics_scrape)
    after=$(metric_in "$snap" cross_validation_requests_total "method=\"${METHOD}\"")
    note "requests_total{$METHOD}" "${before} -> ${after}"
    # The discriminating series: it moves only when a request was actually
    # cross-validated. A build that loaded policies from this block-free config
    # would move it here, and this is the check that would catch it.
    check "the cross-validation counter did NOT move" "$after" "$before"

    echo ""
    echo "[3] a caller that DOES send the headers still gets cross-validation"
    before="$after"
    call "$METHOD" "[\"$(addr 72)\",\"$BLOCK\"]" \
        -H 'lava-cross-validation-max-participants: 3' \
        -H 'lava-cross-validation-agreement-threshold: 2' >/dev/null
    note "status" "$(hdr status)"
    note "all-providers" "$(hdr all-providers)"
    note "agreeing-providers" "$(hdr agreeing-providers)"
    check "the header-driven path is untouched" "$(hdr status)" "success"
    check "the caller's fan-out was honoured" "$(count_csv "$(hdr all-providers)")" "3"
    after=$(metric cross_validation_requests_total "method=\"${METHOD}\"")
    note "requests_total{$METHOD}" "${before} -> ${after}"
    check_gt "and NOW the counter moves — the caller opted in" "$after" "$before"

    echo ""
    echo "[4] providers with no group-label fold into the implicit 'default' group"
    echo "    — so a header-driven request never fails for lack of diversity"
    check "no diversity failure reason" "$(hdr failure-reason)" ""

    echo ""
    echo "[5] the degenerate caller request the docs warn about"
    echo "    (max-participants 1 + agreement-threshold 1: a 'quorum' of one)"
    call "$METHOD" "[\"$(addr 73)\",\"$BLOCK\"]" \
        -H 'lava-cross-validation-max-participants: 1' \
        -H 'lava-cross-validation-agreement-threshold: 1' >/dev/null
    note "status" "$(hdr status)"
    note "all-providers" "$(hdr all-providers)"
    note "agreeing-providers" "$(hdr agreeing-providers)"
    check "it reports success" "$(hdr status)" "success"
    check "having compared nothing — one provider queried" "$(count_csv "$(hdr all-providers)")" "1"
    echo "    A client that needs real corroboration must read the provider lists,"
    echo "    not 'status' alone. An operator policy is what forecloses this."

    echo ""
    echo "[6] the policy-driven surfaces stay absent"
    snap=$(metrics_scrape)
    printf '%s' "$snap" | grep '^smartrouter_cross_validation_requests_total' | sed 's/^/        /'
    # mismatch_total needs a successful content OUTLIER; this lane injects no
    # dissent, so its absence proves nothing on its own and is only reported.
    note "mismatch series present" \
        "$(printf '%s' "$snap" | grep -c '^smartrouter_cross_validation_mismatch_total') (no dissent injected, so 0 either way)"
    check "no policy-driven failures were recorded" \
        "$(metric_in "$snap" cross_validation_failures_total)" "0"

    echo ""
    if [[ "$FAIL" -eq 0 ]]; then
        echo "  UC-7 PASS — existing deployments and existing callers need zero changes."
    else
        echo "  UC-7 FAIL — $FAIL check(s) did not hold. Router left running for inspection."
        echo "  logs: $ROUTER_LOG"
    fi
}

bring_up() {
    echo "============================================"
    echo "Cross-Validation — DEFAULT LANE (UC-7)"
    echo "============================================"
    echo "  router     0.0.0.0:${ROUTER_PORT}   (ETH1 jsonrpc)"
    echo "  metrics    127.0.0.1:${METRICS_PORT}"
    echo "  upstreams  provider_simulator eth-sim 1-6, NO group labels"
    echo "  policies   none — this is the whole point"
    echo "============================================"
    echo ""

    for tool in jq curl python3 lsof screen; do
        command_exists "$tool" || die "'$tool' is required."
    done
    [[ -f "$SPEC_FILE" ]] || die "spec not found: $SPEC_FILE"

    echo "[Setup] reclaiming this lane's previous run (if any)"
    reclaim_owned "$PIDFILE" "router"
    reclaim_by_identity "$ROUTER_PORT" "$CONFIG_FILE" "router"
    screen -S "$ROUTER_SCREEN" -X quit >/dev/null 2>&1 || true
    sleep 1

    require_free_ports "ROUTER_PORT=3499 METRICS_PORT=7893 $0" "$ROUTER_PORT" "$METRICS_PORT"

    echo "[Setup] installing binaries"
    make -C "$PROJECT_ROOT" install || die "make install failed"

    echo ""
    sim_ensure "$SIM_LOG"
    fleet_clean

    echo ""
    echo "[Setup] generating ${CONFIG_REL}"
    write_config
    echo "  $(wc -c < "$CONFIG_FILE" | tr -d ' ') bytes, ${FLEET_SIZE} providers, no cross-validation block"

    echo ""
    echo "[Setup] starting the Smart Router (log -> $ROUTER_LOG)"
    screen -d -m -S "$ROUTER_SCREEN" bash -c "cd \"$PROJECT_ROOT\" && source ~/.bashrc; smartrouter \
$CONFIG_REL \
--log-level debug \
--use-static-spec \"$SPEC_FILE\" \
--metrics-listen-address ':$METRICS_PORT' \
--skip-websocket-verification 2>&1 | tee \"$ROUTER_LOG\"" && sleep 0.25

    echo "[Setup] waiting for the router ..."
    wait_healthy "$ROUTER_PORT" "$ROUTER_SCREEN" || {
        echo "Tail of $ROUTER_LOG:"
        tail -n 30 "$ROUTER_LOG" 2>/dev/null | sed 's/^/    /'
        die "the router never answered 200 on /lava/health"
    }
    record_owned "$PIDFILE" "$ROUTER_PORT" "router" || exit 1

    # A 200 from /lava/health is not a provider-readiness signal: the listener
    # starts in a goroutine while provider validation continues. Step [3] asks for
    # three providers, so a partially-validated fleet would fail it as
    # insufficient-capacity under a banner claiming UC-7 is broken.
    echo "[Setup] waiting for the providers to become selectable ..."
    wait_providers "$ROUTER_PORT" 3 "$WARM_METHOD" \
        || echo "  WARNING: three providers were not selectable in time; checks may fail on capacity"
    echo "  router ready"
}

cheat_sheet() {
    cat <<EOF

============================================
Router is running — manual commands
============================================

Plain relay — no cross-validation, no headers on the way back:
  curl -si -X POST http://127.0.0.1:${ROUTER_PORT} -H 'Content-Type: application/json' \\
    -d '{"jsonrpc":"2.0","method":"${METHOD}","params":["0x00000000000000000000000000000000000000ff","${BLOCK}"],"id":1}' \\
    | grep -i '^lava-'

The same request, with the caller opting in as it always could:
  curl -si -X POST http://127.0.0.1:${ROUTER_PORT} -H 'Content-Type: application/json' \\
    -H 'lava-cross-validation-max-participants: 3' \\
    -H 'lava-cross-validation-agreement-threshold: 2' \\
    -d '{"jsonrpc":"2.0","method":"${METHOD}","params":["0x00000000000000000000000000000000000000fe","${BLOCK}"],"id":1}' \\
    | grep -i '^lava-cross-validation'

The two configs run the same six providers, so this diff is the feature and
nothing else — the policy block, the group labels, and the listen port:
  diff debugging/smartrouter_cv_default.yml debugging/smartrouter_cv_demo.yml

Re-run the checks / teardown:
  $0 --check
  $0 --stop
============================================
EOF
}

HDR=$(mktemp)
trap 'rm -f "$HDR"' EXIT

case "${1:-}" in
    --stop)   teardown; exit 0 ;;
    --status)
        echo "router  :${ROUTER_PORT}   $(router_healthy && echo UP || echo DOWN)"
        echo "sim     ${SIM_CONTROL}  $(sim_up && echo UP || echo DOWN)"
        [[ -f "$PIDFILE" ]] && echo "owned router pid: $(cut -d'|' -f1 "$PIDFILE")"
        exit 0 ;;
    --check)
        router_healthy || die "no router answering 200 on :${ROUTER_PORT}/lava/health. Bring the lane up first: $0"
        checks ;;
    "")
        bring_up
        [[ "$SKIP_CHECK" == "1" ]] || checks
        cheat_sheet ;;
    *)
        echo "usage: $0 [--check|--status|--stop]"; exit 2 ;;
esac

[[ "$FAIL" -eq 0 ]] && exit 0 || exit 1
