#!/bin/bash
# Two-zone secondary-cache integration lane (docs/SECONDARY-CACHE-DESIGN.md §14).
#
# Reproduces the PRD's Kraken topology on one machine:
#
#   internal zone: router-internal (:3361) --cache-be cache-internal (:20101)
#   external zone: router-external (:3360) --cache-be cache-external (:20100)
#                                          --secondary-cache-be cache-internal (:20101, read-only)
#
# Demo flow: a relay through the INTERNAL router warms the internal cache; the
# same request against the EXTERNAL router then misses its own (empty) primary,
# hits the internal cache through the read-only secondary tier, is served as
# "Cached", and is backfilled into the external primary — which serves the next
# repeat directly. RUN_DEMO=1 executes and verifies the flow automatically.
__dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "$__dir"/../useful_commands.sh
. "${__dir}"/../vars/variables.sh

LOGS_DIR=${__dir}/../../debugging/logs
mkdir -p $LOGS_DIR
LOGS_DIR=$(cd "$LOGS_DIR" && pwd)
rm $LOGS_DIR/*.log 2>/dev/null || true

PROJECT_ROOT=$(cd ${__dir}/../.. && pwd)
CONFIG_EXTERNAL="$PROJECT_ROOT/config/smartrouter_examples/smartrouter_eth_zone_external.yml"
CONFIG_INTERNAL="$PROJECT_ROOT/config/smartrouter_examples/smartrouter_eth_zone_internal.yml"

if [[ "$REGENERATE_CONFIG" == "1" ]]; then
    echo "REGENERATE_CONFIG=1: removing existing zone configs..."
    rm -f "$CONFIG_EXTERNAL" "$CONFIG_INTERNAL" 2>/dev/null || true
fi

# Kill any running smartrouter processes / screens from a previous setup
killall smartrouter 2>/dev/null || true
sleep 1
killall screen 2>/dev/null || true
sleep 1
screen -wipe
sleep 1

echo "============================================"
echo "Smart Router SECONDARY CACHE Test Setup"
echo "============================================"
echo "Topology: two zones, two caches, two routers"
echo "  internal: router :3361 -> cache :20101 (read/write)"
echo "  external: router :3360 -> cache :20100 (read/write)"
echo "                         -> cache :20101 (READ-ONLY secondary)"
echo "============================================"
echo ""

echo "[Test Setup] installing all binaries"
make install

echo "[Test Setup] starting cache-external (external zone primary, :20100)"
screen -d -m -S cache_external bash -c "source ~/.bashrc; smartrouter cache \
127.0.0.1:20100 --metrics_address 0.0.0.0:20200 --log_level debug 2>&1 | tee $LOGS_DIR/CACHE_EXTERNAL.log" && sleep 0.25

echo "[Test Setup] starting cache-internal (internal zone primary / external secondary, :20101)"
screen -d -m -S cache_internal bash -c "source ~/.bashrc; smartrouter cache \
127.0.0.1:20101 --metrics_address 0.0.0.0:20201 --log_level debug 2>&1 | tee $LOGS_DIR/CACHE_INTERNAL.log" && sleep 0.25

sleep 2
for port in 20100 20101; do
    if nc -z 127.0.0.1 $port 2>/dev/null; then
        echo "  Cache port $port: LISTENING"
    else
        echo "  WARNING: cache port $port not yet listening (may still be starting)"
    fi
done
echo ""

SPECS_DIR="$PROJECT_ROOT/specs/ethereum.json"
echo "Using static specs: $SPECS_DIR"

# HTTP endpoints only — this lane exercises the cache tiers, not subscriptions.
# ETH_RPC_URL_1 is required; 2/3 are optional extras.
export ETH_RPC_URL_1="${ETH_RPC_URL_1:-https://ethereum-rpc.publicnode.com}"
export ETH_RPC_URL_2="${ETH_RPC_URL_2:-}"
export ETH_RPC_URL_3="${ETH_RPC_URL_3:-}"

if [[ "$ETH_RPC_URL_1" == *"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"* ]]; then
    echo "ERROR: ETH_RPC_URL_1 contains a placeholder — export a real endpoint first."
    exit 1
fi

# emit_config <file> <listen-port> — both zones share the same upstream endpoints;
# what differs is only the listen address (and, at runtime, the cache flags).
emit_config() {
    local file="$1" port="$2"
    cat > "$file" <<EOF
# Generated by init_smartrouter_eth_secondary_cache.sh — two-zone secondary-cache lane.
endpoints:
  - listen-address: "0.0.0.0:${port}"
    chain-id: "ETH1"
    api-interface: "jsonrpc"
    network-address: "0.0.0.0:${port}"

direct-rpc:
  - name: "eth-rpc-1"
    chain-id: "ETH1"
    api-interface: "jsonrpc"
    node-urls:
      - url: "$ETH_RPC_URL_1"
        skip-verifications:
          - chain-id
          - pruning
EOF
    for url in "$ETH_RPC_URL_2" "$ETH_RPC_URL_3"; do
        [[ -z "$url" ]] && continue
        local idx=$(( $(grep -c 'name: "eth-rpc-' "$file") + 1 ))
        cat >> "$file" <<EOF

  - name: "eth-rpc-${idx}"
    chain-id: "ETH1"
    api-interface: "jsonrpc"
    node-urls:
      - url: "$url"
        skip-verifications:
          - chain-id
          - pruning
EOF
    done
}

for cfg in "$CONFIG_EXTERNAL:3360" "$CONFIG_INTERNAL:3361"; do
    file="${cfg%%:*}"; port="${cfg##*:}"
    if [[ -f "$file" && "$REGENERATE_CONFIG" != "1" ]]; then
        echo "Using existing config: $file (REGENERATE_CONFIG=1 to regenerate)"
    else
        echo "Generating config: $file (listen :$port)"
        emit_config "$file" "$port"
    fi
done
echo ""

echo "[Test Setup] starting router-internal (:3361, primary cache :20101)"
screen -d -m -S smartrouter_internal bash -c "cd $PROJECT_ROOT && source ~/.bashrc; smartrouter \
config/smartrouter_examples/smartrouter_eth_zone_internal.yml \
--log-level debug \
--cache-be \"127.0.0.1:20101\" \
--use-static-spec $SPECS_DIR \
--skip-websocket-verification \
--metrics-listen-address ':7780' 2>&1 | tee $LOGS_DIR/SMARTROUTER_INTERNAL.log" && sleep 0.25

echo "[Test Setup] starting router-external (:3360, primary :20100, SECONDARY :20101 read-only)"
screen -d -m -S smartrouter_external bash -c "cd $PROJECT_ROOT && source ~/.bashrc; smartrouter \
config/smartrouter_examples/smartrouter_eth_zone_external.yml \
--log-level debug \
--cache-be \"127.0.0.1:20100\" \
--secondary-cache-be \"127.0.0.1:20101\" \
--secondary-cache-timeout 100ms \
--secondary-cache-mode read-only \
--use-static-spec $SPECS_DIR \
--skip-websocket-verification \
--metrics-listen-address ':7779' 2>&1 | tee $LOGS_DIR/SMARTROUTER_EXTERNAL.log" && sleep 0.25

sleep 3
for name in smartrouter_internal smartrouter_external; do
    if screen -list | grep -q "$name"; then
        echo "  $name screen: RUNNING"
    else
        echo "  ERROR: $name screen failed to start! Check $LOGS_DIR for logs"
        exit 1
    fi
done
echo ""
echo "--- setting up screens done ---"
screen -ls
echo ""

# A fixed, long-finalized mainnet block: deterministic cache key on every router
# (no LATEST/tip involvement) and the finalized long-TTL store on both caches.
DEMO_BODY='{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x112a880",false],"id":1}'

if [[ "$RUN_DEMO" == "1" ]]; then
    echo "============================================"
    echo "RUN_DEMO=1: executing the two-zone flow"
    echo "============================================"
    echo "Waiting 20s for chain-tip establishment on both routers..."
    sleep 20

    echo ""
    echo "Step 1: warm the INTERNAL cache through router-internal (:3361)"
    curl -s -X POST http://127.0.0.1:3361 -H 'Content-Type: application/json' -d "$DEMO_BODY" | head -c 120; echo " ..."
    sleep 1

    echo ""
    echo "Step 2: same request via router-external (:3360) — expect a SECONDARY hit (served as Cached)"
    STEP2_HDR=$(curl -s -D - -o /dev/null -X POST http://127.0.0.1:3360 -H 'Content-Type: application/json' -d "$DEMO_BODY" | grep -i 'lava-provider-address')
    echo "  $STEP2_HDR"

    echo ""
    echo "Step 3: repeat immediately — expect a PRIMARY hit (backfill landed)"
    STEP3_HDR=$(curl -s -D - -o /dev/null -X POST http://127.0.0.1:3360 -H 'Content-Type: application/json' -d "$DEMO_BODY" | grep -i 'lava-provider-address')
    echo "  $STEP3_HDR"

    echo ""
    echo "Per-tier cache metrics on router-external (:7779):"
    curl -s http://127.0.0.1:7779/metrics | grep -E 'smartrouter_cache_(success|requests)_total' | grep -v ' 0$' | sed 's/^/  /'
    echo ""
    echo "PASS criteria:"
    echo "  - Steps 2 and 3 both show 'Cached'"
    echo "  - smartrouter_cache_success_total{...cache_tier=\"secondary\"} >= 1  (step 2)"
    echo "  - smartrouter_cache_success_total{...cache_tier=\"primary\"}   >= 1  (step 3)"
    echo "============================================"
fi

echo ""
echo "============================================"
echo "Secondary Cache Setup Complete!"
echo "============================================"
echo "cache-external:  127.0.0.1:20100 (metrics :20200) — external zone primary"
echo "cache-internal:  127.0.0.1:20101 (metrics :20201) — internal primary / external SECONDARY"
echo "router-internal: 0.0.0.0:3361 (metrics :7780)"
echo "router-external: 0.0.0.0:3360 (metrics :7779)"
echo ""
echo "Manual demo (or rerun with RUN_DEMO=1):"
echo ""
echo "Step 1: warm the internal cache via the INTERNAL router:"
echo "  curl -X POST http://127.0.0.1:3361 \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '$DEMO_BODY'"
echo ""
echo "Step 2: same request via the EXTERNAL router — primary misses, SECONDARY hits:"
echo "  curl -v -X POST http://127.0.0.1:3360 \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '$DEMO_BODY'"
echo "  # response header: Lava-Provider-Address: Cached"
echo ""
echo "Step 3: repeat step 2 — the PRIMARY now hits (populator backfilled it):"
echo "  # same curl; verify the tier split in metrics:"
echo "  curl -s http://127.0.0.1:7779/metrics | grep smartrouter_cache_success_total"
echo "  # expect one series with cache_tier=\"secondary\" (step 2) and one with"
echo "  # cache_tier=\"primary\" (step 3)"
echo ""
echo "Verify read-only: the router NEVER writes the secondary — watch for zero"
echo "SetRelay activity from router-external in the internal cache log:"
echo "  tail -f $LOGS_DIR/CACHE_INTERNAL.log | grep -i 'Cache Set'"
echo ""
echo "Watch the secondary tier decide:"
echo "  tail -f $LOGS_DIR/SMARTROUTER_EXTERNAL.log | grep -i 'secondary cache'"
echo ""
echo "To Stop All Services:"
echo "  killall smartrouter"
echo "  screen -wipe"
echo ""
echo "============================================"
echo "Ready to test!"
echo "============================================"
