#!/bin/bash
__dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "$__dir"/../useful_commands.sh

# Use absolute paths for logs
LOGS_DIR=${__dir}/../../debugging/logs
mkdir -p "$LOGS_DIR"
LOGS_DIR=$(cd "$LOGS_DIR" && pwd)
rm "$LOGS_DIR"/*.log 2>/dev/null || true

# Save project root for later use
PROJECT_ROOT=$(cd "${__dir}/../.." && pwd)

echo "============================================"
echo "Smart Router Direct RPC (Stellar via PublicNode)"
echo "============================================"
echo "Mode: DIRECT RPC (no Stellar providers)"
echo "Upstream: PublicNode REST"
echo "============================================"
echo ""

# Kill any running smartrouter processes (best-effort)
killall smartrouter 2>/dev/null || true
sleep 1

# Kill all screen sessions (best-effort)
killall screen 2>/dev/null || true
sleep 1
screen -wipe
sleep 1

echo "[Test Setup] installing all binaries"
make install

echo ""
echo "[Test Setup] skipping local node — using PublicNode endpoints"

# Start cache service (optional but recommended)
echo ""
echo "[Test Setup] starting smart router cache service"
screen -d -m -S cache bash -c "source ~/.bashrc; smartrouter cache \
127.0.0.1:20100 --metrics_address 0.0.0.0:20200 --log_level debug 2>&1 | tee \"$LOGS_DIR/CACHE.log\"" && sleep 0.25
sleep 2

# PublicNode upstream endpoints (TLS)
STELLAR_REST_LOCAL="https://g.w.lavanet.xyz/gateway/xlmt/rest/e980cb6d55f0c8c8b35e02b2aa328481"

# Ports. 3360/3361 and 7779 are used by the lavap consumer that the other
# pre_setup scripts start; that process binds 127.0.0.1 and wins for IPv4 traffic,
# so curl silently reaches lavap instead of the smart router. Use our own ports.
SR_REST_PORT=3390
SR_METRICS_PORT=7789

# Specs used for routing/parsing. Loaded straight from the same repo production
# reads, so local behaviour matches production exactly and there is no local copy
# to drift. stellar.json there defines XLM (mainnet) and XLMT (testnet); XLMT
# imports XLM from the same file, so no cosmos/tendermint bundle is needed.
#
# Override with a local path when working offline or testing a spec edit, e.g.
#   SPECS_DIR=/path/to/lava-specs/stellar.json ./init_smartrouter_stellar.sh
SPECS_DIR="${SPECS_DIR:-https://github.com/Magma-Devs/lava-specs}"

case "$SPECS_DIR" in
	http://*|https://*)
		echo "Specs source (remote): $SPECS_DIR"
		;;
	*)
		IFS=',' read -r -a SPEC_FILES <<< "$SPECS_DIR"
		for spec_file in "${SPEC_FILES[@]}"; do
			if [ ! -e "$spec_file" ]; then
				echo "✗ ERROR: Spec path not found: $spec_file"
				exit 1
			fi
		done
		echo "Specs source (local): $SPECS_DIR"
		;;
esac

# Generate smart router config (1 upstream REST endpoint -> local node)
CONFIG_FILE="$PROJECT_ROOT/config/smartrouter_examples/smartrouter_stellar.yml"
echo ""
# Always regenerate. This file is script-owned; preserving it meant a stale or
# broken config survived every re-run and silently produced the same startup error.
echo "Generating smart router config: $CONFIG_FILE"
echo "Upstream REST (LCD):     $STELLAR_REST_LOCAL"

cat > "$CONFIG_FILE" <<EOF
# Smart Router Direct RPC Configuration (Stellar testnet)
# Mode: Direct connections to the upstream Horizon endpoint (no Stellar providers!)
#
# This file is generated by: scripts/pre_setups/init_smartrouter_stellar.sh
#
# chain-id MUST be a spec index that exists in specs/stellar.json:
#   XLM  = Stellar mainnet
#   XLMT = Stellar testnet   <- the upstream URL below is the xlmt gateway
# There is no spec indexed "STELLAR"; using it aborts startup with
# "spec not found for chainId".
#
# Every listener under 'endpoints' needs an api-interface, and each one needs a
# matching 'direct-rpc' entry with the SAME chain-id AND the SAME api-interface,
# or startup aborts with "no direct-rpc endpoints configured for listener".

endpoints:
  - network-address: "0.0.0.0:$SR_REST_PORT"
    chain-id: "XLMT"
    api-interface: "rest"

direct-rpc:
  # 1 upstream REST endpoint (Horizon testnet, TLS)
  - name: "stellar-publicnode-rest-1"
    chain-id: "XLMT"
    api-interface: "rest"
    node-urls:
      - url: "$STELLAR_REST_LOCAL"
        timeout: 10s
        skip-verifications:
          - pruning

EOF

# Verify config file was created
echo "Verifying generated config file..."
if [ -f "$CONFIG_FILE" ]; then
	FILE_SIZE=$(wc -c < "$CONFIG_FILE")
	echo "✓ Smart router config exists: $CONFIG_FILE (size: $FILE_SIZE bytes)"
else
	echo "✗ ERROR: Smart router config NOT found: $CONFIG_FILE"
	exit 1
fi

echo ""
echo "[Test Setup] starting Smart Router (DIRECT RPC mode, REST + gRPC + Tendermint RPC)"
screen -d -m -S smartrouter bash -c "cd \"$PROJECT_ROOT\" && source ~/.bashrc; smartrouter \
config/smartrouter_examples/smartrouter_stellar.yml \
--log-level trace \
--cache-be \"127.0.0.1:20100\" \
--use-static-spec \"$SPECS_DIR\" \
--metrics-listen-address ':$SR_METRICS_PORT' \
--maximum-streams-per-connection 10 \
--min-relay-timeout 5s 2>&1 | tee \"$LOGS_DIR/SMARTROUTER_STELLAR.log\"" && sleep 0.25

sleep 3

echo "Verifying smart router screen session..."
if screen -list | grep -q "smartrouter"; then
	echo "✓ Smart router screen is running"
else
	echo "✗ ERROR: Smart router screen failed to start!"
	echo "  Check $LOGS_DIR/SMARTROUTER_STELLAR.log for errors"
	exit 1
fi

echo ""
echo "--- setting up screens done ---"
screen -ls

echo ""
echo "============================================"
echo "Smart Router (Stellar via PublicNode) Setup Complete!"
echo "============================================"
echo "Upstream REST:          $STELLAR_REST_LOCAL"
echo "Cache:                    127.0.0.1:20100 (metrics: 20200)"
echo "Smart Router REST:        http://127.0.0.1:$SR_REST_PORT (metrics: $SR_METRICS_PORT)"
echo "Chain ID:                 XLMT (Stellar testnet)"
echo ""
echo "🔬 Test Commands (REST):"
echo "  # Latest ledger (GET)"
echo "  curl \"http://127.0.0.1:$SR_REST_PORT/ledgers?order=desc&limit=1\" | head -c 300"
echo ""
echo "  # Submit a transaction (POST, form-encoded) - the MAG content-type path"
echo "  curl -i http://127.0.0.1:$SR_REST_PORT/transactions \\"
echo "    -H 'Content-Type: application/x-www-form-urlencoded' \\"
echo "    --data-urlencode 'tx=<base64-xdr>'"
echo ""
echo "📊 Monitor Logs:"
echo "  tail -f $LOGS_DIR/SMARTROUTER_STELLAR.log"
echo ""
echo "✋ To Stop All Services:"
echo "  killall smartrouter"
echo "  screen -wipe"
echo "============================================"

